inst/shiny-examples/ShinyItemAnalysis/DDplot.R
inst/shiny-examples/ShinyItemAnalysis/plotDistractorAnalysis.R
inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

Upravene verze. Pridana funkce DDplot pro plotovani difficulty/discrimination grafu

Upravena verze - server, ui, DDplot

---

inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

Byl upraven tab Data - věci se zobrazuji tak, jak bylo požadováno.
Item slidery - byly přidány tam, kde bylo požadováno, a zbytek byl rozpojen.

Jak hou patch 1

---

inst/shiny-examples/ShinyItemAnalysis/server.R

Ploty v DIF/IRT Lord a DIF/IRT Raju neukazovaly číslo itemu. Vyřešeno

Vykreslování grafů v DIF/IRT Lord a DIF/IRT Raju

---

inst/shiny-examples/ShinyItemAnalysis/Rcode_ShinyItemAnalysis.R
inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

Zakomentovani source funkci. Pridani souboru s vybranym kodem Rcode_ShinyItemAnalysis.R

Kod a package verze

---

inst/shiny-examples/ShinyItemAnalysis/ui.R

Opravil jsem překlepy, které jsem dokázal najít.

Oprava překlepů

---

inst/shiny-examples/ShinyItemAnalysis/server.R

- uprava multinomicke regrese pro 0/1 data
- uprava datatables

Multinomial model pro 2 kategorie, data tables

---

inst/shiny-examples/ShinyItemAnalysis/reporthtml.Rmd
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd
inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

Myslím si, že by mohl pomoci revert, kód doplním rychle.
Je možné, že mi nějak špatně proběhl update, ač jsem updatovat před commitem, např. předpřipravený kód od Adély na download corrplotu jsem neviděl a vypisoval jsem jej sám.

Revert "Wright Map v reportu, download corrplot"

---

DESCRIPTION
NEWS
R/DDplot.R
R/DistractorAnalysis.R
R/plotDIFLogistic.R
R/plotDistractorAnalysis.R
inst/CITATION
inst/shiny-examples/ShinyItemAnalysis/DDplot.R
inst/shiny-examples/ShinyItemAnalysis/DistractorAnalysis.R
inst/shiny-examples/ShinyItemAnalysis/plotDIFLogistic.R
inst/shiny-examples/ShinyItemAnalysis/plotDistractorAnalysis.R
inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R
man/DDplot.Rd
man/DistractorAnalysis.Rd
man/dataMedical.Rd
man/dataMedicalkey.Rd
man/dataMedicaltest.Rd
man/plotDIFLogistic.Rd
man/plotDIFirt.Rd
man/plotDistractorAnalysis.Rd
man/startShinyItemAnalysis.Rd

Version 1.1.1.

---

inst/shiny-examples/ShinyItemAnalysis/server.R

Object downloadHandler() revised in order to make online typesetting and
downloading of reports possible.

downloading of reports fixed

---

inst/shiny-examples/ShinyItemAnalysis/server.R

Reverts patriciamar/ShinyItemAnalysis#196

Revert "downloading of reports fixed"

---

inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

- pridano ICC
- pridana rovnice 4PL modelu
- pridana rovnice ICC pro 4PL model
- pridany download buttons

ICC a hratky s IRT

---

NEWS
README.md
inst/shiny-examples/ShinyItemAnalysis/ui.R

I added some minor changes and notes. Merge if you like them.

reports - additions

---

DESCRIPTION
NEWS
R/DistractorAnalysis.R
R/plotDistractorAnalysis.R
README.md
inst/shiny-examples/ShinyItemAnalysis/DistractorAnalysis.R
inst/shiny-examples/ShinyItemAnalysis/plotDistractorAnalysis.R
inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R
inst/shiny-examples/ShinyItemAnalysis/www/bootstrap.css
man/DistractorAnalysis.Rd
man/plotDistractorAnalysis.Rd
man/startShinyItemAnalysis.Rd

- predictive validity section added
- functions DistractorAnalysis() and plotDistractorAnalysis() updated by
'matching' argument
- predictive outcome can be now downloaded
- better description of data download is provided
- NEWS file updated
- DESCRIPTION file updated

Version 1.1.4

---

inst/shiny-examples/ShinyItemAnalysis/ui.R
inst/shiny-examples/ShinyItemAnalysis/www/busy.js

Warning via message box before report downloading was added. It pops up
when a user clicks on the "Generate Report" button.

message box warning before report downloading

---

inst/shiny-examples/ShinyItemAnalysis/www/busy.js

One sentence, "Press "OK" to start report generating.", added to the
alert message box popping up when report downloading is started.

updating of message box warnings

---

inst/shiny-examples/ShinyItemAnalysis/ui.R
inst/shiny-examples/ShinyItemAnalysis/www/margins_and_paddings.css

I added a blind CSS class ensuring there will be always a space between body text content and the footer.

a space between footer and content added

---

inst/shiny-examples/ShinyItemAnalysis/www/margins_and_paddings.css

Last lines of code chunks in tabs were partially overlaped by the footer; fixed.

better fit of code chunks position vs. footer

---

inst/shiny-examples/ShinyItemAnalysis/ui.R

- histograms of total scores for groups
- irt curves toys

Figures side by side

---

inst/shiny-examples/ShinyItemAnalysis/reporthtml.Rmd
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd
inst/shiny-examples/ShinyItemAnalysis/server.R

I added some text to reports.
I also fixed bug (nobody noticed) with DIF group vector. Now it should
work without any problem.

Reports - text

---

DESCRIPTION
NEWS
README.md
inst/CITATION
inst/shiny-examples/ShinyItemAnalysis/DIF.R
inst/shiny-examples/ShinyItemAnalysis/Validity.R
inst/shiny-examples/ShinyItemAnalysis/reporthtml.Rmd
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd
inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

v1.2.3 - first part

---

inst/shiny-examples/ShinyItemAnalysis/reporthtml.Rmd
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd
inst/shiny-examples/ShinyItemAnalysis/server.R

v1.2.3. - part 3

---

inst/shiny-examples/ShinyItemAnalysis/reporthtml.Rmd
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd

v1.2.3 - part 4

---

inst/shiny-examples/ShinyItemAnalysis/TraditionalAnalysis.R

bug in distractor report fixed

v1.2.3 - last part

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/IRT.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

IRT training, IRT comparison

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/IRT.R
inst/shiny-examples/ShinyItemAnalysis/reporthtml.Rmd
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd

In all IRT models table with parameters includes all parameters a, b, c,
d. The same for reports.

IRT tables

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/ui.R

IRT training and comparison

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/Validity.R
inst/shiny-examples/ShinyItemAnalysis/reporthtml.Rmd
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd
inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

Option for cluster method was added for corrplot. This is also done in
reports.

Corrplot - cluster method option

---

inst/shiny-examples/ShinyItemAnalysis/Regression.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

Bug in multinomial regression when only two possible choices in data are
present was fixed.

Multinomial regression bug fix

---

DESCRIPTION
NEWS
README.md
inst/shiny-examples/ShinyItemAnalysis/ui.R

Selected R code for IRT training was added

Selected R code for IRT training

---

inst/shiny-examples/ShinyItemAnalysis/DIF.R

Table for difNLR parameters is displayed properly

Bug fixing

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/DIF.R
inst/shiny-examples/ShinyItemAnalysis/reporthtml.Rmd
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd
inst/shiny-examples/ShinyItemAnalysis/server.R

Reports improvements

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/IRT.R
inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

IRT training changes

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/IRT.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

version 1.2.6.-3 - IRT training

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/IRT.R
inst/shiny-examples/ShinyItemAnalysis/ui.R
inst/shiny-examples/ShinyItemAnalysis/www/bootstrap.css

v1.2.6-4 - IRT section

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/server/Validity.R

Bug in dendrogram

---

NEWS
R/plotDIFLogistic.R
man/plotDIFLogistic.Rd

Function plotDIFLogistic() now handles user-specified matching criterion.

Bug in plotDIFLogistic()

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/reporthtml.Rmd
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd
inst/shiny-examples/ShinyItemAnalysis/server.R
inst/shiny-examples/ShinyItemAnalysis/server/DIF.R
inst/shiny-examples/ShinyItemAnalysis/server/Summary.R
inst/shiny-examples/ShinyItemAnalysis/ui.R

Histograms are now in plotly mode. Selected R code was updated. t-test was added for comparison of total scores (also in reports).

Total scores for groups

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/server/Regression.R

Delta method was implemented. Cumulative regression now handle data with missing levels of scores (e.g. 1-3-4, 1-2-3-4, etc.)

Delta method for cumulative

---

NEWS
R/DistractorAnalysis.R
R/plotMultinomial.R

v1.3.0-13 - part 2

---

NEWS
R/plotMultinomial.R
inst/shiny-examples/ShinyItemAnalysis/server/DIF.R

v1.3.0-15 - part 2

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/packages.sty
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd

v1.3.0-15 - part 3

---

NEWS
inst/shiny-examples/ShinyItemAnalysis/reportpdf.Rmd

PDF reports - bug fixing
